sudo: required

# Tell travis we need a copy of docker running
services:
  - docker

# Build our image using Dockerfile.dev
before_install:
  - docker build -t robbypelssers/docker-react -f Dockerfile.dev .

# Tell Travis how to run our test suite
# We pass -e CI=true to make sure the test suite exits after running
script:
  - docker run -e CI=true robbypelssers/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "frontend"
  env: "frontend-env"
  bucket_name: "elasticbeanstalk-eu-west-1-926372350997"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
